# Generated by Django 5.0 on 2026-04-08 01:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mymodel',
            name='hls_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='uploaded', max_length=20),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='title',
            field=models.CharField(default='Untitled', max_length=255),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
