# Generated by Django 5.0 on 2026-04-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mymodel_created_at_mymodel_hls_path_mymodel_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='hls_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
